services:
  - type: web
    name: my-simple-php-app
    env: php
    region: oregon
    plan: free
    buildCommand: ""
    startCommand: php -S 0.0.0.0:10000 -t .
    autoDeploy: true
    branch: main
